import { strToU8, zipSync } from "fflate";
export type ExportPost = { id: string; message: string; displayName: string; createdAt: string | null; photoCount: number; unsupportedPhotos: boolean };
export const escapeHtml = (value: string) => value.replace(/[&<>"']/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char]!);
export function exportArchive(name: string, posts: ExportPost[], photos: Record<string, Uint8Array>) {
  const entries: Record<string, Uint8Array> = { ...photos };
  entries["messages.json"] = strToU8(JSON.stringify({ property: name, exportedAt: new Date().toISOString(), posts }, null, 2));
  entries["README.txt"] = strToU8("Open index.html to read this part offline. Download every part from the export page. Only currently visible, unrestricted memories are included. Internal records and private feedback are excluded. Older external photos marked unsupportedPhotos are not included. An export is a copy and cannot reflect subsequent edits or deletions.");
  entries["index.html"] = strToU8(`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src 'self'; style-src 'unsafe-inline'"><title>${escapeHtml(name)}</title><style>body{font:18px system-ui;max-width:760px;margin:2rem auto;padding:1rem}article{border-bottom:1px solid #ccc;padding:1rem 0}p{white-space:pre-wrap}img{max-width:100%;height:auto}</style><h1>${escapeHtml(name)}</h1>${posts.map(post => `<article><h2>${escapeHtml(post.displayName || "Guest")}</h2><p>${escapeHtml(post.createdAt || "")}</p><p>${escapeHtml(post.message)}</p>${Array.from({ length: post.photoCount }, (_, index) => `<img src="photos/${post.id}-${index}.webp" alt="Guest photo ${index + 1}">`).join("")}${post.unsupportedPhotos ? "<p>Older external photos could not be included in this part.</p>" : ""}</article>`).join("")}</html>`);
  return zipSync(entries, { level: 0 });
}
