const {chromium}=require('C:/Users/clbbe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs');const assert=require('node:assert/strict');
(async()=>{
const browser=await chromium.launch({channel:'msedge',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1050}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
const seed=JSON.parse(fs.readFileSync(__dirname+'/seed.json','utf8'));
await page.addInitScript(seed=>{window.testDisk=JSON.stringify(seed);window.testWrites=0;window.showOpenFilePicker=async()=>[{name:'DigiStayBook-tasks.json',requestPermission:async()=> 'granted',getFile:async()=>({text:async()=>window.testDisk}),createWritable:async()=>{let pending;return{write:async v=>pending=v,close:async()=>{window.testDisk=pending;window.testWrites++;}}}}];},seed);
await page.goto('file://192.168.1.71/nas/projects/DigiStayBook/business-operations/DigiStayBook-task-board.html');
assert.equal(await page.locator('#tasks tr').count(),53);
await page.locator('#connect').click();
await page.locator('#date-launch').fill('2026-11-02');await page.locator('#date-launch').dispatchEvent('change');
await page.locator('#search').fill('A-19');
assert.match(await page.locator('#tasks').innerText(),/26 Oct 2026/);
await page.locator('[data-owner="A-19"]').fill('Owner');await page.locator('[data-owner="A-19"]').dispatchEvent('change');
await page.waitForFunction(()=>testWrites>0);
assert.equal(await page.evaluate(()=>JSON.parse(testDisk).tasks.find(t=>t.id==='A-19').owner),'Owner');
await page.locator('[data-edit="A-19"]').click();await page.locator('#dateMode').selectOption('fixed');await page.locator('#fixedDate').fill('2026-10-20');await page.locator('#taskForm button[type=submit]').click();
await page.locator('#date-launch').fill('2026-11-09');await page.locator('#date-launch').dispatchEvent('change');assert.match(await page.locator('#tasks').innerText(),/20 Oct 2026/);
await page.locator('[data-complete="A-19"]').click();await page.locator('#statusFilter').selectOption('Done');assert.equal(await page.locator('[data-complete="A-19"]').isChecked(),true);
await page.waitForFunction(()=>JSON.parse(testDisk).tasks.find(t=>t.id==='A-19').status==='Done');
await page.reload();await page.locator('#statusFilter').selectOption('Done');await page.locator('#search').fill('A-19');assert.equal(await page.locator('[data-complete="A-19"]').isChecked(),true);
await page.locator('#connect').click();
await page.evaluate(()=>{const disk=JSON.parse(testDisk);disk.tasks[0].notes='Edited by another person';testDisk=JSON.stringify(disk);});
await page.locator('#statusFilter').selectOption('all');await page.locator('[data-owner="A-19"]').fill('Other owner');await page.locator('[data-owner="A-19"]').dispatchEvent('change');
await page.waitForFunction(()=>document.getElementById('conflict').style.display==='block');
assert.equal(await page.evaluate(()=>JSON.parse(testDisk).tasks[0].notes),'Edited by another person');
await page.locator('#conflictReload').click();await page.waitForFunction(()=>document.getElementById('conflict').style.display==='none');
await page.locator('#search').fill('');await page.locator('#statusFilter').selectOption('');
await page.screenshot({path:__dirname+'/preview.png',fullPage:false});
await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
assert.deepEqual(errors,[]);await browser.close();console.log('PASS: 53 imported tasks, weekday targets, fixed-date override, assignment, completion, refresh persistence, shared saves and conflict protection; desktop/mobile layout. Shared filesystem API simulated; actual NAS write permission requires browser connection.');
})().catch(e=>{console.error(e);process.exit(1)});
